version: '3'
services:

  #App
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    container_name: demix-app
#    environment:
#      - "VIRTUAL_HOST=${DEMIXER_VIRTUAL_HOST}"
#      - "LETSENCRYPT_HOST=${DEMIXER_VIRTUAL_HOST}"
#      - "LETSENCRYPT_EMAIL="


  #Webserver
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./demixer:/var/www
    ports:
      - ${HTTP_PORT}:80
    container_name: demix-webproxy

networks:
  default:
    external:
      name: ${NETWORK}
